# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  posthome:
    image: posthome
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5286:5286
